### ISSUE TITLE
Installation (registration) problem

### ISSUE THREAD

**Issue by ThomasBreuer** [gap-packages/JupyterKernel#107]
The package documentation says in Section 1.2 that one can register the GAP Jupyter kernel with `python setup.py install --user`.
I got messages of the kind `No module named notebook.nbextensions` in this step, and the registration did not work.
This problem disappeared when I used `python3` instead of `python2`.
Should the manual require `python3`?
On the other hand, the example shown in Section 1.3-1 suggests that also `python2` should work.

(By the way, the manual should say that the `python` call must be executed in the directory of the package, where the file `setup.py` resides.
And the manual should say that it might be necessary to repeat the registration step after upgrading the `JupyterKernel` package to a new version.)

**Comment by ZachNewbery** [comment]
Should be fixed by #106

**Comment by alex-konovalov** [comment]
Also #119 provides more detailed installation instructions, and tells that some steps should be repeated after upgrade.
