### ISSUE TITLE
The output from PreImagesRepresentative is not JupyterRenderable

### ISSUE THREAD

**Issue by BBischof** [gap-packages/JupyterKernel#110]
I saw in the documentation that we should report these here. Unfortunately, I cant seem to inspect the object with any functions either, so I can seem to get it via attributes :/

**Comment by alex-konovalov** [comment]
Thanks @BBischof. Can you at least print it with `Print`? Perhaps that could help you as a workaround? Also, if you could provide an example, we can look at possible ways to inspect it.

**Comment by alex-konovalov** [comment]
The new version, released today, has improved rendering of some outputs. I've tried the example from the GAP tutorial, and it works. Will close this, but please let us know if your objects are still not printed in an informative way. You can try the new version on Binder by clicking on a launch Binder button. 
![Screenshot 2021-08-04 at 11 44 02](https://user-images.githubusercontent.com/5751387/128168387-cc2a29be-371b-4294-b17c-60b8440559ef.png)
