### ISSUE TITLE
JUPYTER_KernelStart_GAP

### ISSUE THREAD

**Issue by johnbamberg** [gap-packages/JupyterKernel#113]
I have the error:

Error, Variable: 'JUPYTER_KernelStart_GAP' must have a value

Jupyter works fine, all packages load in my GAP installation, and the paths are correct. I am using MAC OSX (Catalina). What should be "configfile" in the argument to this function? 

I have the same error when I run the jupyter-kernel-gap script:

% jupyter-kernel-gap
GAP Jupyter Kernel Starting using gap
fail
Error, Variable: 'JUPYTER_KernelStart_GAP' must have a value
not in any function at *stdin*:2

**Comment by johnbamberg** [comment]
If it helps, this is my kernel.json:
{"argv": ["jupyter-kernel-gap", "{connection_file}"], "display_name": "GAP 4", "language": "gap", "codemirror_mode": "gap", "env": {"PS1": "$"}, "interrupt_mode": "message" }

**Comment by johnbamberg** [comment]
@alex-konovalov It returns true.

**Comment by alex-konovalov** [comment]
@johnbamberg could you also check https://github.com/gap-packages/JupyterKernel/issues/74, in particular steps 6-7?

**Comment by johnbamberg** [comment]
Thanks: I did this already, because it is a wonderful post you've made. Steps 6-7 are fine ... my paths are correct.

**Comment by alex-konovalov** [comment]
Ok, that definitely differs from my machine:
```
$ jupyter-kernel-gap 
GAP Jupyter Kernel Starting using gap
true
Error, no method found! For debugging hints type ?Recovery from NoMethodFound
Error, no 1st choice method found for `ReadByte' on 1 arguments
The 1st argument is 'fail' which might point to an earlier problem
```
You know that you are not using this script though - the way is to start Jupyter and the you should be able to see GAP when you create a new notebook.

What `jupyter kernelspec list` says? See example at https://gap-packages.github.io/JupyterKernel/doc/chap1.html#X7CA9D73583D1D456.

**Comment by alex-konovalov** [comment]
Another idea - I think that's a lead. What is the output of 

    echo $JUPYTER_GAP_EXECUTABLE

This is the content of `jupyter-kernel-gap`:

```
#!/bin/sh

if [ -n "$JUPYTER_GAP_EXECUTABLE" ] ; then
  GAP=$JUPYTER_GAP_EXECUTABLE
elif [ -z "$GAP" ] ; then
  GAP=gap
fi

echo "GAP Jupyter Kernel Starting using $GAP"
exec $GAP -q -T --alwaystrace <<EOF
   LoadPackage("JupyterKernel");
   JUPYTER_KernelStart_GAP("$1");
   QUIT_GAP(0);
EOF
```

The line `echo "GAP Jupyter Kernel Starting using $GAP"` outputs `$GAP` and in your case it shows `gap` so it seems to ignore `$JUPYTER_GAP_EXECUTABLE"` that you define.

**Comment by alex-konovalov** [comment]
P.S. just in case, you have to `source ~/.zshrc` after you made changes for them to take effect in the same terminal session.

**Comment by johnbamberg** [comment]
Thanks @alex-konovalov . Here's the output of each command:
```
jupyter kernelspec list

Available kernels:
  python3    /Users/00044445/Library/Python/3.7/lib/python/site-packages/ipykernel/resources
  gap-4      /Users/00044445/Library/Jupyter/kernels/gap-4
```
```
echo $JUPYTER_GAP_EXECUTABLE

gap -l ".;/Users/00044445/"
```

**Comment by alex-konovalov** [comment]
@johnbamberg so if you do 

    gap -l ".;/Users/00044445/"

then GAP just starts?

**Comment by johnbamberg** [comment]
Yes indeed.

**Comment by alex-konovalov** [comment]
@johnbamberg how are you - did you manage to use Jupyter GAP notebooks after all?

**Comment by johnbamberg** [comment]
Yes, thanks Alex. I started from scratch and it resolved the issue.
