### ISSUE TITLE
Installation under Anaconda

### ISSUE THREAD

**Issue by alex-konovalov** [gap-packages/JupyterKernel#117]
We have tried to install this package (release JupyterKernel 1.3 included in the GAP 4.11.1 distribution) to use with Anaconda Python installation of @xpan-eileen. The obstacle was that it had GAP 4.11.0 already (apparently installed with some SageMath installation). First called `conda remove gap`, then tried to install this kernel with `python setup.py install` and it complained about permissions. @xpan-eileen, I have some ideas what to try next:

a) `python setup.py install --user` may allow that due to the `--user` option

b) if not, then try to replace JupyterKernel 1.3 by a clone of this repository, and install it using
```
pip install .
```
or, if that also fails, using
```
pip install . --user
```
(this was introduced in https://github.com/gap-packages/JupyterKernel/pull/106 by @isuruf).

Pinging @isuruf who may have more relevant advise for Anaconda.

**Comment by isuruf** [comment]
either `b` or `pip install git+https://github.com/gap-packages/JupyterKernel` should work

**Comment by xpan-eileen** [comment]
Thank you @alex-konovalov and @isuruf! I ran isuruf's suggestion directly in JupyterLab and restarted it, now it works perfectly in both JupyterLab and JupyterNotebook.

**Comment by alex-konovalov** [comment]
Wonderful, thanks for confirming @xpan-eileen! So looks like no special instructions for Anaconda are needed for the newest state of the package on GitHub, and so things will become better from the next JupyterKernel release.
