### ISSUE TITLE
Catch SyntaxErrors and SyntaxWarnings

### ISSUE THREAD

**Issue by markuspf** [gap-packages/JupyterKernel#13]
This will need patches in the main GAP repository.

**Comment by pedritomelenas** [comment]
This also affects things like `Exec(less something)` : `less` is performed in the console and waits `q` to end (in the console).

**Comment by pedritomelenas** [comment]
just another example: `Filtered([1..10],x->kk(x));` hangs and produces the following in the terminal

```
Syntax warning: Unbound global variable in stream:1
Filtered([1..10],x->kk(x));                      ^
Error, Variable: 'kk' must have an assigned value in
   called from 
return kk( x ); at stream:1
you can 'return;' after assigning a value
brk>    QUIT_GAP(0);
func( elm ) at /Users/pedro/lib/gap/lib/coll.gi:1416
```

**Comment by markuspf** [comment]
I disabled he break loop now, which gets rid of your hang/crash. Doesn't address the error message problem.

**Comment by pedritomelenas** [comment]
Thanks, this works for the `Filtered` example.
