### ISSUE TITLE
no output from cell evaluation (using Python 3.5)

### ISSUE THREAD

**Issue by dimpase** [gap-packages/JupyterKernel#27]
I have installed Jupyter using `pip3 install jupyter --user` on `4.14.3-gentoo #3 SMP x86_64 Intel(R)` and `JupyterKernel` as described in the manual (and all the needed packages, naturally).

I do not get any echo from commands in input cells, only if I do `Print()` then I get to see things. This is not how it is meant to work, right?

Also, if I do not complete a statement with `;` then the echo from execution is a message on red background saying `An error happened`.

**Comment by cmdawson** [comment]
I also have the issue with statements not completed with `;` . I see the gap error in the jupyter log  
```[I 09:41:30.343 NotebookApp] Adapting to protocol v5.3 for kernel 88b304d5-3d8d-4b71-85e5-d4b04be5ff61
Syntax error: ; expected in stream:1
```
but then no further communication with the kernel is possible.

Otherwise everything works perfectly (and is awesome)

**Comment by haraldschilly** [comment]
I'm curious, is this fixed or part of an ongoing pull request? This is one of the issues we had with that kernel on cocalc.com and I want to know if we should try again.

**Comment by dimpase** [comment]
It would be good to know what GAP kernel bug this is. Thanks!

**Comment by cmdawson** [comment]
I believe it is this one

https://github.com/gap-system/gap/issues/2487
