### ISSUE TITLE
shell script in `/etc/jupyter/jupyter-kernel-gap`

### ISSUE THREAD

**Issue by ThomasBreuer** [gap-packages/JupyterKernel#29]
The shell script in `/etc/jupyter/jupyter-kernel-gap`
calls with highest priority the GAP that is given by the return value of `which gap`.
The GAP version specified by the environment variable `JUPYTER_GAP_EXECUTABLE`
is used only if the result of `which gap` is empty.

I think it should be the other way round.
That is, `JUPYTER_GAP_EXECUTABLE` should allow one to specify a particular GAP version,
and a default GAP (if available) can be called if no such version is specified.

(The current script works if `gap` is defined only as an alias,
but if an executable `gap` is found in the user's path then this GAP gets called.)

**Comment by markuspf** [comment]
I agree. Fixed in b75f71a337da7c383e9a1acc5d8375f9b27b7659

Word of warning: the kernel is currently broken (more than usual) on the `master` branch.

**Comment by markuspf** [comment]
Coming to think of it, I'll add the variable `GAP` as well (in between `JUPYTER_GAP_EXECUTABLE`, and looking in the path), as this seems to be used at least by @fingolfin's scripts (and is a natural choice).
