### ISSUE TITLE
`GAPInfo;` has no output

### ISSUE THREAD

**Issue by ssiccha** [gap-packages/JupyterKernel#48]

**Comment by alex-konovalov** [comment]
GAPInfo.PackagesInfo does not work either. OTOH, e.g. GAPInfo.PackagesInfo.ace[1] and GAPInfo.Version work.

**Comment by markuspf** [comment]
If you inspect the messy output at the terminal that your jupyter is running on, you can see that something does not like some unicode that is sent over the wire.

I added `JUPYTER_LogProtocol` in #52 to be able to more easily get hold of what is happening on the wire.

**Comment by markuspf** [comment]
@ChrisJefferson has tracked this down to an issue in the `json` package. I hope a fix is forthcoming.

**Comment by markuspf** [comment]
The current `master` branch of https://github.com/gap-packages/json fixes this issue. A release will be out soon.
