### ISSUE TITLE
Clean Kernel Shutdown

### ISSUE THREAD

**Issue by markuspf** [gap-packages/JupyterKernel#7]
Make sure the Kernel shuts down cleanly and clears up all the Zmq sockets so that restarting it doesn't run into "address already in use" problems.

**Comment by pedritomelenas** [comment]
Also restarting the kernel may fail; probably related to this.

**Comment by markuspf** [comment]
This should solved by e8a6a073716063a7abb5de12692a26ebe8f3cc2f due to be released in the next week.
