### ISSUE TITLE
Jupyter Kernel complains: "Error, Function: number of arguments must be 4 (not 3)"

### ISSUE THREAD

**Issue by enriqueartal** [gap-packages/JupyterKernel#75]
I have compiled the develop version of GAP, in linux (fedora 28). I installed Jupyter Kernel and it complains with the error in the message. By the way at some point the message was "Error, Function: number of arguments must be 3 (not 2)".

**Comment by enriqueartal** [comment]
Some information I forgot to add. It happens in the Jupyter notebook, not at the time of installation, when executing any GAP order.

**Comment by markuspf** [comment]
This should be resolved with the most recent release.

**Comment by enriqueartal** [comment]
Right! Thanks!
