### ISSUE TITLE
Syntax errors shouldn't printed as normal output

### ISSUE THREAD

**Issue by ssiccha** [gap-packages/JupyterKernel#78]
I guess this happens because the functions that print the syntax errors still print to `"*errout*"`.

**Comment by markuspf** [comment]
This is true, and it is technically not a bug in the JupyterKernel, but in GAP, and I expect it to be fixed there.

**Comment by ssiccha** [comment]
This is resolved by the yet-to-be-merged PR gap-system/gap#3043.

**Comment by alex-konovalov** [comment]
Seems to be fixed by now, indeed. 
![Screenshot 2021-08-04 at 20 05 09](https://user-images.githubusercontent.com/5751387/128240066-32e72575-d7a5-41b3-bc5d-16d6a25e4bdf.png)
